name: Push to Telegram

on:
  push:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: appleboy/telegram-action@v0.1.2
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          message_thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
          message: |
            New commit pushed to repository on branch: ${{ github.ref_name }}
            - **Message**: ${{ github.event.head_commit.message }}
            - **Author**: Rugsafe Core Team
            - [View Commit](${{ github.event.head_commit.url }})
