name: Push to Telegram

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            New commit pushed to repository:
            - **Message**: ${{ github.event.head_commit.message }}
            - **Author**: ${{ github.event.head_commit.author.name }}
            - [View Commit](${{ github.event.head_commit.url }})
